### ISSUE TITLE
numpy 2.0 compatibility

### ISSUE THREAD

**Issue by effigies** [nipy/nitime#218]
https://github.com/conda-forge/nitime-feedstock/pull/32 indicates (unsurprisingly) that there are numpy 2.0 compatibilities.

With numpy 2.0 in RC phase, it's probably time to try to fix these.

I don't have the time at the moment, unfortunately.

**Comment by arokem** [comment]
For the time being maybe we should make a release that pins to numpy<2.0?
WDYT?

**Comment by effigies** [comment]
That sounds like a good idea.

**Comment by arokem** [comment]
Is this resolved by #217 ?

**Comment by larsoner** [comment]
Oh I guess not. Wheels are built against 2.0 but probably not tested against 2.0 actually 🤦 

For example there are still `np.sctypes` in the code which no longer exists. I can open a quick PR to at least have one CI run with NumPy 2.0rc2 if that would help

**Comment by effigies** [comment]
#217 also didn't resolve #214. I think we can add the nitime test suite to the cibuildwheel post-build step, to avoid adding a new entry/dimension to the regular test matrix.

https://cibuildwheel.pypa.io/en/stable/options/#test-command

**Comment by larsoner** [comment]
>  I think we can add the nitime test suite to the cibuildwheel post-build step, to avoid adding a new entry/dimension to the regular test matrix.

Good call, I'll add this to #221. It's not 100% trivial, though, because 2.0 hasn't officially landed yet. I could separate the `tool.cibuildwheel.test-requires` to use different NumPy versions for testing different wheels if that would help. This is similar to how in https://github.com/nipy/nitime/pull/221 I just install NumPy 2.1.dev for the Python 3.11 run only.

**Comment by effigies** [comment]
Is aarch only supported by numpy 2? I think they've had wheels for ages, and we should be able to test against numpy 1.

**Comment by larsoner** [comment]
> Is aarch only supported by numpy 2? I think they've had wheels for ages, and we should be able to test against numpy 1.

No it's supported on 1.26 for example as well. I was just saying "enabling tests during wheel build" won't trivially solve the "need to test against NumPy 2.0" problem. But agreed that enabling tests during wheel building would help with #219 either way.

**Comment by effigies** [comment]
Sorry, yeah. I was just going where the conversation was, and looking at the issue title, I see why you assumed numpy 2.0.
